services:
  web:
    platform: linux/amd64 # Explicitly set for TDX
    image: ymc182/shade-agent:latest@sha256:2a2a42092d18d099db78561757d62a439df6e50ba52d96994cda81b0ec4494b0
    env_file:
      - .env.development.local
    ports:
      - "3000:3000"
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
